import type { ResourceDefinition } from '@svadmin/core';

export const resources: ResourceDefinition[] = [
  // ─── Admin CRUD Resources ────────────────────────────────────
  {
    name: 'channels',
    label: '渠道',
    icon: 'radio',
    primaryKey: 'id',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'name', label: '名称', type: 'text', required: true, searchable: true },
      { key: 'type', label: '类型', type: 'select', options: [
        { label: 'OpenAI', value: 1 },
        { label: 'Midjourney Proxy', value: 2 },
        { label: 'Azure OpenAI', value: 3 },
        { label: 'Ollama', value: 4 },
        { label: 'Midjourney Proxy Plus', value: 5 },
        { label: 'Custom Channel', value: 8 },
        { label: 'Anthropic Claude', value: 14 },
        { label: 'Baidu', value: 15 },
        { label: 'Zhipu (GLM)', value: 16 },
        { label: 'Alibaba (DashScope)', value: 17 },
        { label: 'Xunfei', value: 18 },
        { label: 'OpenRouter', value: 20 },
        { label: 'Tencent Hunyuan', value: 23 },
        { label: 'Google Gemini', value: 24 },
        { label: 'Moonshot', value: 25 },
        { label: 'Perplexity', value: 27 },
        { label: 'LingYiWanWu', value: 31 },
        { label: 'AWS Bedrock', value: 33 },
        { label: 'Cohere', value: 34 },
        { label: 'MiniMax', value: 35 },
        { label: 'Suno API', value: 36 },
        { label: 'Dify', value: 37 },
        { label: 'Jina', value: 38 },
        { label: 'Cloudflare Worker', value: 39 },
        { label: 'SiliconCloud', value: 40 },
        { label: 'Vertex AI', value: 41 },
        { label: 'Mistral AI', value: 42 },
        { label: 'DeepSeek', value: 43 },
        { label: 'VolcEngine', value: 45 },
        { label: 'Baidu V2', value: 46 },
        { label: 'xAI', value: 48 },
        { label: 'Coze', value: 49 },
        { label: 'Kling', value: 50 },
        { label: 'Jimeng', value: 51 },
        { label: 'Vidu', value: 52 },
        { label: 'Sora', value: 55 },
        { label: 'Replicate', value: 56 },
        { label: 'Codex', value: 57 },
        { label: 'ComfyUI', value: 100 },
        { label: 'NVIDIA NIM (Legacy)', value: 1001 },
        { label: 'Flux (Legacy)', value: 1002 },
        { label: 'Udio (Legacy)', value: 1003 },
        { label: 'Dakka (Legacy)', value: 1004 },
      ] },
      { key: 'baseUrl', label: 'Base URL', type: 'url', required: true },
      { key: 'key', label: '密钥', type: 'textarea', showInList: false, required: true },
      { key: 'models', label: '模型', type: 'tags', showInList: false },
      { key: 'modelMapping', label: '模型映射', type: 'textarea', showInList: false },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '在线', value: 1 },
        { label: '测试中', value: 2 },
        { label: '已禁用', value: 3 },
      ], filterable: true },
      { key: 'endpointType', label: '端点(防同步)', type: 'select', options: [
        { label: '自动匹配 (随雷达同步)', value: 'auto' },
        { label: '固定文本 (禁止同步)', value: 'chat' },
        { label: '原生 Gemini', value: 'native-gemini' },
      ] },
      { key: 'keyConcurrencyLimit', label: '单Key并发', type: 'number' },
      { key: 'priority', label: '优先级', type: 'number' },
      { key: 'weight', label: '权重', type: 'number' },
      { key: 'priceRatio', label: '渠道倍率', type: 'number' },
      { key: 'groups', label: '允许分组', type: 'tags', showInList: false },
      { key: 'testModel', label: '测试模型', type: 'text', showInList: false },
      { key: 'openaiOrganization', label: 'OpenAI Organization', type: 'text', showInList: false },
      { key: 'responseTime', label: '响应时间(ms)', type: 'number', showInForm: false },
      { key: 'balance', label: '余额', type: 'number', showInForm: false },
      { key: 'autoBan', label: '自动禁用', type: 'number', showInList: false },
      { key: 'tag', label: '标签', type: 'text', showInList: false },
      { key: 'statusCodeMapping', label: '状态码映射', type: 'textarea', showInList: false },
      { key: 'paramOverride', label: '参数覆盖', type: 'textarea', showInList: false },
      { key: 'headerOverride', label: '请求头覆盖', type: 'textarea', showInList: false },
      { key: 'remark', label: '备注', type: 'textarea', showInList: false },
      { key: 'setting', label: '高级设置', type: 'textarea', showInList: false },
      { key: 'channelInfo', label: '渠道信息(JSON)', type: 'textarea', showInList: false, showInForm: false },
      { key: 'createdAt', label: '创建时间', type: 'date', showInForm: false },
      { key: 'updatedAt', label: '更新时间', type: 'date', showInForm: false },
    ],
    defaultSort: { field: 'id', order: 'desc' },
  },
  {
    name: 'users',
    label: '用户',
    icon: 'users',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'username', label: '用户名', type: 'text', required: true, searchable: true },
      { key: 'password', label: '密码', type: 'password', showInList: false },
      { key: 'role', label: '角色', type: 'select', options: [
        { label: '普通用户', value: 1 },
        { label: '管理员', value: 10 },
      ] },
      { key: 'quota', label: '总额度', type: 'number' },
      { key: 'usedQuota', label: '已用额度', type: 'number', showInForm: false },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: 1 },
        { label: '禁用', value: 2 },
      ] },
    ],
    defaultSort: { field: 'id', order: 'desc' },
  },
  {
    name: 'tokens',
    label: '令牌',
    icon: 'key',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'name', label: '名称', type: 'text', required: true, searchable: true },
      { key: 'key', label: 'Key', type: 'text', showInForm: false },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: 1 },
        { label: '禁用', value: 2 },
      ] },
      { key: 'remainQuota', label: '剩余额度', type: 'number' },
      { key: 'unlimitedQuota', label: '无限额度', type: 'boolean' },
      { key: 'usedQuota', label: '已用额度', type: 'number', showInForm: false },
      { key: 'models', label: '绑定模型', type: 'tags' },
      { key: 'modelLimitsEnabled', label: '启用模型限制', type: 'boolean' },
      { key: 'allowIps', label: 'IP 白名单', type: 'textarea', showInList: false },
      { key: 'rateLimit', label: 'RPM', type: 'number' },
      { key: 'expiredAt', label: '过期时间', type: 'date', showInList: false },
      { key: 'tokenGroup', label: '令牌分组', type: 'text', showInList: false },
      { key: 'crossGroupRetry', label: '跨组重试', type: 'boolean', showInList: false },
      { key: 'subnet', label: '子网白名单', type: 'text', showInList: false },
      { key: 'orgId', label: '组织 ID', type: 'number', showInList: false },
      { key: 'accessedAt', label: '最近访问', type: 'date', showInForm: false },
      { key: 'userId', label: '所属用户 ID', type: 'number' },
      { key: 'creatorName', label: '创建人', type: 'text', showInForm: false },
    ],
    defaultSort: { field: 'id', order: 'desc' },
  },
  {
    name: 'user-groups',
    label: '分组',
    icon: 'folder',
    primaryKey: 'key',
    fields: [
      { key: 'key', label: '分组标识', type: 'text', required: true, searchable: true },
      { key: 'name', label: '名称', type: 'text', required: true },
      { key: 'description', label: '描述', type: 'textarea' },
      { key: 'allowedModels', label: '允许模型', type: 'tags', showInList: false },
      { key: 'deniedModels', label: '禁止模型', type: 'tags', showInList: false },
      { key: 'allowedChannelTypes', label: '允许渠道类型', type: 'tags', showInList: false },
      { key: 'deniedChannelTypes', label: '禁止渠道类型', type: 'tags', showInList: false },
      { key: 'allowedPackages', label: '允许套餐', type: 'tags', showInList: false },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '启用', value: 1 },
        { label: '禁用', value: 2 },
      ] },
    ],
  },
  {
    name: 'packages',
    label: '套餐',
    icon: 'package',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'name', label: '套餐名', type: 'text', required: true, searchable: true },
      { key: 'price', label: '价格', type: 'number' },
      { key: 'durationDays', label: '时长(天)', type: 'number' },
      { key: 'models', label: '包含模型', type: 'tags', showInList: false },
      { key: 'isPublic', label: '是否公开', type: 'boolean' },
    ],
    defaultSort: { field: 'id', order: 'desc' },
  },
  {
    name: 'redemptions',
    label: '兑换码',
    icon: 'gift',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'name', label: '名称', type: 'text', required: true },
      { key: 'key', label: '兑换码', type: 'text' },
      { key: 'quota', label: '额度', type: 'number', required: true },
      { key: 'count', label: '次数', type: 'number' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: 1 },
        { label: '失效', value: 2 },
      ] },
    ],
    defaultSort: { field: 'id', order: 'desc' },
  },
  {
    name: 'rate-limits',
    label: '限流策略',
    icon: 'shield',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'name', label: '策略名', type: 'text', required: true },
      { key: 'rpm', label: 'RPM', type: 'number' },
      { key: 'rph', label: 'RPH', type: 'number' },
      { key: 'concurrent', label: '并发数', type: 'number' },
    ],
    defaultSort: { field: 'id', order: 'desc' },
  },

  // ─── Virtual Resources (custom pages, no CRUD) ───────────────
  // These are intercepted by CustomAutoTable and rendered as custom Svelte pages.
  {
    name: 'system-options',
    label: '系统设置',
    icon: 'settings',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    fields: [],
  },
  {
    name: 'models',
    label: '模型状态',
    icon: 'cpu',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    fields: [],
  },
  {
    name: 'playground',
    label: 'API 测试',
    icon: 'play',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    fields: [],
  },
  {
    name: 'content-management',
    label: '内容管理',
    icon: 'file-text',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    fields: [],
  },
  {
    name: 'pricing-editor',
    label: '倍率管理',
    icon: 'coins',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    fields: [],
  },
  {
    name: 'performance-monitor',
    label: '性能监控',
    icon: 'activity',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    fields: [],
  },
  {
    name: 'vendors',
    label: '供应商',
    icon: 'building',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'name', label: '名称', type: 'text', required: true, searchable: true },
      { key: 'type', label: '类型', type: 'number' },
      { key: 'baseUrl', label: 'Base URL', type: 'url' },
      { key: 'logoUrl', label: 'Logo URL', type: 'url', showInList: false },
      { key: 'description', label: '描述', type: 'textarea', showInList: false },
      { key: 'createdAt', label: '创建时间', type: 'date', showInForm: false },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'logs',
    label: '日志',
    icon: 'scroll-text',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'modelName', label: '模型', type: 'text', searchable: true },
      { key: 'username', label: '用户', type: 'text' },
      { key: 'channelName', label: '渠道', type: 'text' },
      { key: 'promptTokens', label: '输入Token', type: 'number' },
      { key: 'completionTokens', label: '输出Token', type: 'number' },
      { key: 'quotaCost', label: '消耗额度', type: 'number' },
      { key: 'costUsd', label: '费用(USD)', type: 'text' },
      { key: 'statusCode', label: '状态码', type: 'number', filterable: true },
      { key: 'isStream', label: '流式', type: 'boolean' },
      { key: 'channelId', label: '渠道ID', type: 'number' },
      { key: 'createdAt', label: '时间', type: 'date', showInForm: false },
    ],
    defaultSort: { field: 'id', order: 'desc' },
  },
  {
    name: 'models-meta',
    label: '模型管理',
    icon: 'cpu',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'modelName', label: '模型名', type: 'text', required: true, searchable: true },
      { key: 'type', label: '类型', type: 'select', options: [
        { label: '对话', value: 'chat' },
        { label: '图片', value: 'image' },
        { label: '视频', value: 'video' },
        { label: '音频', value: 'audio' },
        { label: '嵌入', value: 'embedding' },
        { label: '重排', value: 'rerank' },
        { label: '审核', value: 'moderation' },
      ] },
      { key: 'endpoint', label: '端点', type: 'text' },
      { key: 'displayName', label: '显示名', type: 'text' },
      { key: 'tags', label: '标签', type: 'tags' },
    ],
    defaultSort: { field: 'modelName', order: 'asc' },
  },
];
