import type { ResourceDefinition } from '@svadmin/core';

export const resources: ResourceDefinition[] = [
  // ─── Admin CRUD Resources ────────────────────────────────────
  {
    name: 'channels',
    label: '渠道',
    icon: 'radio',
    primaryKey: 'id',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'name', label: '名称', type: 'text', required: true, searchable: true },
      { key: 'type', label: '类型', type: 'select', options: [
        { label: 'OpenAI', value: 1 },
        { label: 'Azure OpenAI', value: 8 },
        { label: 'Anthropic', value: 14 },
        { label: 'Baidu', value: 15 },
        { label: 'Zhipu (BigModel)', value: 16 },
        { label: 'Alibaba (DashScope)', value: 17 },
        { label: 'Xunfei', value: 18 },
        { label: 'Gemini', value: 23 },
        { label: 'Midjourney', value: 24 },
        { label: 'Jina', value: 25 },
        { label: 'Suno', value: 26 },
        { label: 'DeepSeek', value: 31 },
        { label: 'Cloudflare Worker', value: 33 },
        { label: 'Flux', value: 34 },
        { label: 'Udio', value: 35 },
        { label: 'NVIDIA NIM', value: 41 },
        { label: 'Dakka', value: 42 },
        { label: 'ComfyUI', value: 100 },
      ] },
      { key: 'baseUrl', label: 'Base URL', type: 'url', required: true },
      { key: 'key', label: '密钥', type: 'textarea', showInList: false, required: true },
      { key: 'models', label: '模型', type: 'tags', showInList: false },
      { key: 'modelMapping', label: '模型映射', type: 'textarea', showInList: false },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '在线', value: 1 },
        { label: '测试中', value: 2 },
        { label: '已禁用', value: 3 },
      ], filterable: true },
      { key: 'endpointType', label: '端点(防同步)', type: 'select', options: [
        { label: '自动匹配 (随雷达同步)', value: 'auto' },
        { label: '固定文本 (禁止同步)', value: 'chat' },
        { label: '原生 Gemini', value: 'native-gemini' },
      ] },
      { key: 'keyConcurrencyLimit', label: '单Key并发', type: 'number' },
      { key: 'priority', label: '优先级', type: 'number' },
      { key: 'weight', label: '权重', type: 'number' },
      { key: 'priceRatio', label: '渠道倍率', type: 'number' },
      { key: 'groups', label: '允许分组', type: 'tags', showInList: false },
      { key: 'testModel', label: '测试模型', type: 'text', showInList: false },
      { key: 'openaiOrganization', label: 'OpenAI Organization', type: 'text', showInList: false },
      { key: 'responseTime', label: '响应时间(ms)', type: 'number', showInForm: false },
      { key: 'balance', label: '余额', type: 'number', showInForm: false },
      { key: 'autoBan', label: '自动禁用', type: 'number', showInList: false },
      { key: 'tag', label: '标签', type: 'text', showInList: false },
      { key: 'statusCodeMapping', label: '状态码映射', type: 'textarea', showInList: false },
      { key: 'paramOverride', label: '参数覆盖', type: 'textarea', showInList: false },
      { key: 'headerOverride', label: '请求头覆盖', type: 'textarea', showInList: false },
      { key: 'remark', label: '备注', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'id', order: 'desc' },
  },
  {
    name: 'users',
    label: '用户',
    icon: 'users',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'username', label: '用户名', type: 'text', required: true, searchable: true },
      { key: 'password', label: '密码', type: 'password', showInList: false },
      { key: 'role', label: '角色', type: 'select', options: [
        { label: '普通用户', value: 1 },
        { label: '管理员', value: 10 },
      ] },
      { key: 'quota', label: '总额度', type: 'number' },
      { key: 'usedQuota', label: '已用额度', type: 'number', showInForm: false },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: 1 },
        { label: '禁用', value: 2 },
      ] },
    ],
    defaultSort: { field: 'id', order: 'desc' },
  },
  {
    name: 'tokens',
    label: '令牌',
    icon: 'key',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'name', label: '名称', type: 'text', required: true, searchable: true },
      { key: 'key', label: 'Key', type: 'text', showInForm: false },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: 1 },
        { label: '禁用', value: 2 },
      ] },
      { key: 'remainQuota', label: '剩余额度', type: 'number' },
      { key: 'unlimitedQuota', label: '无限额度', type: 'boolean' },
      { key: 'usedQuota', label: '已用额度', type: 'number', showInForm: false },
      { key: 'models', label: '绑定模型', type: 'tags' },
      { key: 'modelLimitsEnabled', label: '启用模型限制', type: 'boolean' },
      { key: 'allowIps', label: 'IP 白名单', type: 'textarea', showInList: false },
      { key: 'rateLimit', label: 'RPM', type: 'number' },
      { key: 'expiredAt', label: '过期时间', type: 'date', showInList: false },
      { key: 'tokenGroup', label: '令牌分组', type: 'text', showInList: false },
      { key: 'crossGroupRetry', label: '跨组重试', type: 'boolean', showInList: false },
      { key: 'accessedAt', label: '最近访问', type: 'date', showInForm: false },
      { key: 'userId', label: '所属用户 ID', type: 'number' },
      { key: 'creatorName', label: '创建人', type: 'text', showInForm: false },
    ],
    defaultSort: { field: 'id', order: 'desc' },
  },
  {
    name: 'user-groups',
    label: '分组',
    icon: 'folder',
    primaryKey: 'key',
    fields: [
      { key: 'key', label: '分组标识', type: 'text', required: true, searchable: true },
      { key: 'name', label: '名称', type: 'text', required: true },
      { key: 'description', label: '描述', type: 'textarea' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '启用', value: 1 },
        { label: '禁用', value: 2 },
      ] },
    ],
  },
  {
    name: 'packages',
    label: '套餐',
    icon: 'package',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'name', label: '套餐名', type: 'text', required: true, searchable: true },
      { key: 'price', label: '价格', type: 'number' },
      { key: 'durationDays', label: '时长(天)', type: 'number' },
      { key: 'models', label: '包含模型', type: 'tags', showInList: false },
      { key: 'isPublic', label: '是否公开', type: 'boolean' },
    ],
    defaultSort: { field: 'id', order: 'desc' },
  },
  {
    name: 'redemptions',
    label: '兑换码',
    icon: 'gift',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'name', label: '名称', type: 'text', required: true },
      { key: 'key', label: '兑换码', type: 'text' },
      { key: 'quota', label: '额度', type: 'number', required: true },
      { key: 'count', label: '次数', type: 'number' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: 1 },
        { label: '失效', value: 2 },
      ] },
    ],
    defaultSort: { field: 'id', order: 'desc' },
  },
  {
    name: 'rate-limits',
    label: '限流策略',
    icon: 'shield',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '60px' },
      { key: 'name', label: '策略名', type: 'text', required: true },
      { key: 'rpm', label: 'RPM', type: 'number' },
      { key: 'rph', label: 'RPH', type: 'number' },
      { key: 'concurrent', label: '并发数', type: 'number' },
    ],
    defaultSort: { field: 'id', order: 'desc' },
  },

  // ─── Virtual Resources (custom pages, no CRUD) ───────────────
  // These are intercepted by CustomAutoTable and rendered as custom Svelte pages.
  {
    name: 'system-options',
    label: '系统设置',
    icon: 'settings',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    fields: [],
  },
  {
    name: 'models',
    label: '模型状态',
    icon: 'cpu',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    fields: [],
  },
  {
    name: 'playground',
    label: 'API 测试',
    icon: 'play',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    fields: [],
  },
];
