data_directory = '/var/lib/postgresql/17/main'
hba_file = '/etc/postgresql/17/main/pg_hba.conf'
listen_addresses = '*'
port = 5432
max_connections = 100
shared_buffers = 128MB
shared_preload_libraries = pg_cron
cron.database_name = postgres
