import {
    bigint,
    boolean,
    date,
    decimal,
    integer,
    jsonb,
    pgTable,
    serial,
    text,
    timestamp,
    uuid,
    varchar,
} from 'drizzle-orm/pg-core';

export const userGroups = pgTable('user_groups', {
    key: varchar('key', { length: 50 }).primaryKey(),
    name: varchar('name', { length: 100 }).notNull(),
    description: text('description'),
    allowedChannelTypes: jsonb('allowed_channel_types').$type<number[]>().default([]),
    deniedChannelTypes: jsonb('denied_channel_types').$type<number[]>().default([]),
    allowedModels: jsonb('allowed_models').$type<string[]>().default([]),
    deniedModels: jsonb('denied_models').$type<string[]>().default([]),
    allowedPackages: jsonb('allowed_packages').$type<number[]>().default([]),
    status: integer('status').notNull().default(1),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const organizations = pgTable('organizations', {
    id: serial('id').primaryKey(),
    slug: varchar('slug', { length: 80 }).unique(),
    name: varchar('name', { length: 120 }).notNull(),
    billingEmail: text('billing_email'),
    quota: bigint('quota', { mode: 'number' }).notNull().default(0),
    usedQuota: bigint('used_quota', { mode: 'number' }).notNull().default(0),
    allowedModels: jsonb('allowed_models').$type<string[]>().notNull().default([]),
    deniedModels: jsonb('denied_models').$type<string[]>().notNull().default([]),
    allowedSubnets: text('allowed_subnets').notNull().default(''),
    quotaAlarmThreshold: integer('quota_alarm_threshold').notNull().default(80),
    alertThresholdPct: integer('alert_threshold_pct').notNull().default(80),
    alertWebhookUrl: text('alert_webhook_url'),
    lastAlertAt: timestamp('last_alert_at', { withTimezone: true }),
    status: integer('status').notNull().default(1),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const users = pgTable('users', {
    id: serial('id').primaryKey(),
    username: text('username').notNull().unique(),
    email: text('email'),
    emailVerified: boolean('email_verified').default(false),
    name: text('name'),
    passwordHash: text('password_hash').notNull().default(''),
    image: text('image'),
    role: integer('role').notNull().default(1),
    orgId: integer('org_id').references(() => organizations.id, { onDelete: 'set null' }),
    quota: bigint('quota', { mode: 'number' }).notNull().default(0),
    usedQuota: bigint('used_quota', { mode: 'number' }).notNull().default(0),
    group: text('group').notNull().default('default'),
    status: integer('status').notNull().default(1),
    currency: text('currency').notNull().default('USD'),
    githubId: text('github_id'),
    lockedUntil: timestamp('locked_until', { withTimezone: true }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const sessions = pgTable('session', {
    id: text('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    token: text('token').notNull().unique(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const tokens = pgTable('tokens', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    orgId: integer('org_id').references(() => organizations.id, { onDelete: 'set null' }),
    name: text('name').notNull(),
    key: text('key').notNull().unique(),
    status: integer('status').notNull().default(1),
    remainQuota: bigint('remain_quota', { mode: 'number' }).notNull().default(-1),
    usedQuota: bigint('used_quota', { mode: 'number' }).notNull().default(0),
    models: jsonb('models').$type<string[] | null>(),
    subnet: text('subnet'),
    allowIps: text('allow_ips'),
    rateLimit: integer('rate_limit').notNull().default(0),
    unlimitedQuota: boolean('unlimited_quota').notNull().default(false),
    modelLimitsEnabled: boolean('model_limits_enabled').notNull().default(false),
    tokenGroup: text('token_group'),
    crossGroupRetry: boolean('cross_group_retry').notNull().default(false),
    accessedAt: timestamp('accessed_at', { withTimezone: true }),
    expiredAt: timestamp('expired_at', { withTimezone: true }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const channels = pgTable('channels', {
    id: serial('id').primaryKey(),
    type: integer('type').notNull().default(1),
    name: text('name').notNull(),
    baseUrl: text('base_url').notNull().default('https://api.openai.com'),
    key: text('key').notNull(),
    models: jsonb('models').$type<string[]>().notNull().default([]),
    modelMapping: jsonb('model_mapping').$type<Record<string, string>>().notNull().default({}),
    weight: integer('weight').notNull().default(1),
    priority: integer('priority').notNull().default(0),
    groups: jsonb('groups').$type<string[] | null>(),
    status: integer('status').notNull().default(1),
    statusMessage: text('status_message'),
    keyStrategy: integer('key_strategy').notNull().default(0),
    keyStatus: jsonb('key_status').$type<Record<string, unknown>>().notNull().default({}),
    keyConcurrencyLimit: integer('key_concurrency_limit').notNull().default(0),
    endpointType: text('endpoint_type').notNull().default('auto'),
    priceRatio: decimal('price_ratio', { precision: 10, scale: 4 }).default('1.0'),
    testModel: text('test_model'),
    openaiOrganization: text('openai_organization'),
    balance: decimal('balance', { precision: 20, scale: 8 }),
    balanceUpdatedAt: timestamp('balance_updated_at', { withTimezone: true }),
    responseTime: integer('response_time'),
    statusCodeMapping: jsonb('status_code_mapping').$type<Record<string, unknown>>().notNull().default({}),
    autoBan: integer('auto_ban').notNull().default(1),
    tag: text('tag'),
    setting: jsonb('setting').$type<Record<string, unknown>>().notNull().default({}),
    paramOverride: jsonb('param_override').$type<Record<string, unknown>>().notNull().default({}),
    headerOverride: jsonb('header_override').$type<Record<string, unknown>>().notNull().default({}),
    remark: text('remark'),
    channelInfo: jsonb('channel_info').$type<Record<string, unknown>>().notNull().default({}),
    testAt: timestamp('test_at', { withTimezone: true }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const rateLimitRules = pgTable('rate_limit_rules', {
    id: serial('id').primaryKey(),
    name: varchar('name', { length: 100 }).notNull(),
    rpm: integer('rpm').default(0),
    rph: integer('rph').default(0),
    concurrent: integer('concurrent').default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const packages = pgTable('packages', {
    id: serial('id').primaryKey(),
    name: varchar('name', { length: 100 }).notNull(),
    description: text('description'),
    price: decimal('price', { precision: 10, scale: 2 }).notNull(),
    durationDays: integer('duration_days').notNull().default(30),
    models: jsonb('models').$type<string[]>().default([]),
    defaultRateLimitId: integer('default_rate_limit_id').references(() => rateLimitRules.id, { onDelete: 'set null' }),
    modelRateLimits: jsonb('model_rate_limits').$type<Record<string, unknown>>().default({}),
    cycleQuota: bigint('cycle_quota', { mode: 'number' }).default(0),
    cycleInterval: integer('cycle_interval').default(1),
    cycleUnit: text('cycle_unit').default('day'),
    cachePolicy: jsonb('cache_policy').$type<Record<string, unknown>>().default({ mode: 'default' }),
    isPublic: boolean('is_public').default(true),
    allowedGroups: jsonb('allowed_groups').$type<string[]>().default([]),
    addedBy: integer('added_by').references(() => users.id, { onDelete: 'set null' }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const redemptions = pgTable('redemptions', {
    id: serial('id').primaryKey(),
    name: text('name').notNull(),
    key: text('key').notNull().unique(),
    quota: bigint('quota', { mode: 'number' }).notNull().default(0),
    count: integer('count').notNull().default(1),
    usedCount: integer('used_count').notNull().default(0),
    status: integer('status').notNull().default(1),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const logs = pgTable('logs', {
    id: serial('id'),
    userId: integer('user_id').notNull(),
    tokenId: integer('token_id'),
    channelId: integer('channel_id'),
    modelName: text('model_name').notNull(),
    quotaCost: bigint('quota_cost', { mode: 'number' }).notNull().default(0),
    promptTokens: integer('prompt_tokens').notNull().default(0),
    completionTokens: integer('completion_tokens').notNull().default(0),
    cachedTokens: integer('cached_tokens').notNull().default(0),
    elapsedMs: integer('elapsed_ms').notNull().default(0),
    isStream: boolean('is_stream').default(false),
    errorMessage: text('error_message'),
    statusCode: integer('status_code').notNull().default(200),
    ipAddress: varchar('ip_address', { length: 45 }),
    userAgent: text('user_agent'),
    traceId: text('trace_id'),
    orgId: integer('org_id').references(() => organizations.id, { onDelete: 'set null' }),
    externalTaskId: text('external_task_id'),
    externalUserId: text('external_user_id'),
    externalWorkspaceId: text('external_workspace_id'),
    externalFeatureType: text('external_feature_type'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const modelMetadata = pgTable('model_metadata', {
    id: serial('id').primaryKey(),
    modelName: text('model_name').notNull().unique(),
    type: text('type').notNull().default('chat'),
    endpoint: text('endpoint'),
    displayName: text('display_name'),
    tags: jsonb('tags').$type<string[]>().default([]),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const options = pgTable('options', {
    key: text('key').primaryKey(),
    value: text('value').notNull().default(''),
});

export const vendors = pgTable('vendors', {
    id: serial('id').primaryKey(),
    name: text('name').notNull(),
    type: integer('type').default(0),
    baseUrl: text('base_url').default(''),
    logoUrl: text('logo_url').default(''),
    description: text('description').default(''),
    config: jsonb('config').$type<Record<string, unknown>>().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const tasks = pgTable('tasks', {
    id: serial('id').primaryKey(),
    type: varchar('type', { length: 50 }).notNull(),
    name: text('name').notNull(),
    description: text('description'),
    status: integer('status').notNull().default(0),
    priority: integer('priority').notNull().default(0),
    progress: integer('progress').notNull().default(0),
    totalItems: integer('total_items').default(0),
    processedItems: integer('processed_items').default(0),
    result: jsonb('result').$type<Record<string, unknown>>(),
    errorMessage: text('error_message'),
    createdBy: integer('created_by').references(() => users.id, { onDelete: 'set null' }),
    startedAt: timestamp('started_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const workflowTemplates = pgTable('workflow_templates', {
    id: uuid('id').primaryKey().defaultRandom(),
    name: text('name').notNull(),
    description: text('description'),
    groupName: text('group_name').default('default'),
    templateJson: jsonb('template_json').notNull(),
    inputParameters: jsonb('input_parameters').$type<unknown[]>().notNull().default([]),
    providerType: integer('provider_type').notNull().default(100),
    userId: uuid('user_id'),
    isPublic: boolean('is_public').default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const userCheckins = pgTable('user_checkins', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    checkinDate: date('checkin_date').notNull(),
    reward: bigint('reward', { mode: 'number' }).notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const schema = {
    channels,
    logs,
    'models-meta': modelMetadata,
    options,
    organizations,
    packages,
    'rate-limits': rateLimitRules,
    redemptions,
    sessions,
    tasks,
    tokens,
    'user-checkins': userCheckins,
    'user-groups': userGroups,
    users,
    vendors,
    'workflow-templates': workflowTemplates,
};

export type DatabaseSchema = typeof schema;
