import {
    bigint,
    bytea,
    boolean,
    date,
    decimal,
    integer,
    jsonb,
    pgTable,
    serial,
    text,
    timestamp,
    uuid,
    varchar,
} from 'drizzle-orm/pg-core';

export const userGroups = pgTable('user_groups', {
    key: varchar('key', { length: 50 }).primaryKey(),
    name: varchar('name', { length: 100 }).notNull(),
    description: text('description'),
    allowedChannelTypes: jsonb('allowed_channel_types').$type<number[]>().default([]),
    deniedChannelTypes: jsonb('denied_channel_types').$type<number[]>().default([]),
    allowedModels: jsonb('allowed_models').$type<string[]>().default([]),
    deniedModels: jsonb('denied_models').$type<string[]>().default([]),
    allowedPackages: jsonb('allowed_packages').$type<number[]>().default([]),
    status: integer('status').notNull().default(1),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const organizations = pgTable('organizations', {
    id: serial('id').primaryKey(),
    slug: varchar('slug', { length: 80 }).unique(),
    name: varchar('name', { length: 120 }).notNull(),
    billingEmail: text('billing_email'),
    quota: bigint('quota', { mode: 'number' }).notNull().default(0),
    usedQuota: bigint('used_quota', { mode: 'number' }).notNull().default(0),
    allowedModels: jsonb('allowed_models').$type<string[]>().notNull().default([]),
    deniedModels: jsonb('denied_models').$type<string[]>().notNull().default([]),
    allowedSubnets: text('allowed_subnets').notNull().default(''),
    quotaAlarmThreshold: integer('quota_alarm_threshold').notNull().default(80),
    alertThresholdPct: integer('alert_threshold_pct').notNull().default(80),
    alertWebhookUrl: text('alert_webhook_url'),
    lastAlertAt: timestamp('last_alert_at', { withTimezone: true }),
    status: integer('status').notNull().default(1),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const users = pgTable('users', {
    id: serial('id').primaryKey(),
    username: text('username').notNull().unique(),
    email: text('email'),
    emailVerified: boolean('email_verified').default(false),
    name: text('name'),
    passwordHash: text('password_hash').notNull().default(''),
    image: text('image'),
    role: integer('role').notNull().default(1),
    orgId: integer('org_id').references(() => organizations.id, { onDelete: 'set null' }),
    quota: bigint('quota', { mode: 'number' }).notNull().default(0),
    usedQuota: bigint('used_quota', { mode: 'number' }).notNull().default(0),
    group: text('group').notNull().default('default'),
    status: integer('status').notNull().default(1),
    currency: text('currency').notNull().default('USD'),
    billingPreference: text('billing_preference').notNull().default('subscription_first'),
    quotaDisplayType: text('quota_display_type').notNull().default('USD'),
    githubId: text('github_id'),
    twoFactorEnabled: boolean('two_factor_enabled').notNull().default(false),
    twoFactorSecret: text('two_factor_secret'),
    twoFactorPendingSecret: text('two_factor_pending_secret'),
    twoFactorBackupCodes: jsonb('two_factor_backup_codes').$type<string[]>().default([]),
    twoFactorPendingBackupCodes: jsonb('two_factor_pending_backup_codes').$type<string[]>().default([]),
    lockedUntil: timestamp('locked_until', { withTimezone: true }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const sessions = pgTable('session', {
    id: text('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    token: text('token').notNull().unique(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const tokens = pgTable('tokens', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    orgId: integer('org_id').references(() => organizations.id, { onDelete: 'set null' }),
    name: text('name').notNull(),
    key: text('key').notNull().unique(),
    status: integer('status').notNull().default(1),
    remainQuota: bigint('remain_quota', { mode: 'number' }).notNull().default(-1),
    usedQuota: bigint('used_quota', { mode: 'number' }).notNull().default(0),
    models: jsonb('models').$type<string[] | null>(),
    subnet: text('subnet'),
    allowIps: text('allow_ips'),
    rateLimit: integer('rate_limit').notNull().default(0),
    unlimitedQuota: boolean('unlimited_quota').notNull().default(false),
    modelLimitsEnabled: boolean('model_limits_enabled').notNull().default(false),
    tokenGroup: text('token_group'),
    crossGroupRetry: boolean('cross_group_retry').notNull().default(false),
    accessedAt: timestamp('accessed_at', { withTimezone: true }),
    expiredAt: timestamp('expired_at', { withTimezone: true }),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const channels = pgTable('channels', {
    id: serial('id').primaryKey(),
    type: integer('type').notNull().default(1),
    name: text('name').notNull(),
    baseUrl: text('base_url').notNull().default('https://api.openai.com'),
    key: text('key').notNull(),
    models: jsonb('models').$type<string[]>().notNull().default([]),
    modelMapping: jsonb('model_mapping').$type<Record<string, string>>().notNull().default({}),
    weight: integer('weight').notNull().default(1),
    priority: integer('priority').notNull().default(0),
    groups: jsonb('groups').$type<string[] | null>(),
    status: integer('status').notNull().default(1),
    statusMessage: text('status_message'),
    keyStrategy: integer('key_strategy').notNull().default(0),
    keyStatus: jsonb('key_status').$type<Record<string, unknown>>().notNull().default({}),
    keyConcurrencyLimit: integer('key_concurrency_limit').notNull().default(0),
    endpointType: text('endpoint_type').notNull().default('auto'),
    priceRatio: decimal('price_ratio', { precision: 10, scale: 4 }).default('1.0'),
    testModel: text('test_model'),
    openaiOrganization: text('openai_organization'),
    balance: decimal('balance', { precision: 20, scale: 8 }),
    balanceUpdatedAt: timestamp('balance_updated_at', { withTimezone: true }),
    responseTime: integer('response_time'),
    statusCodeMapping: jsonb('status_code_mapping').$type<Record<string, unknown>>().notNull().default({}),
    autoBan: integer('auto_ban').notNull().default(1),
    tag: text('tag'),
    setting: jsonb('setting').$type<Record<string, unknown>>().notNull().default({}),
    paramOverride: jsonb('param_override').$type<Record<string, unknown>>().notNull().default({}),
    headerOverride: jsonb('header_override').$type<Record<string, unknown>>().notNull().default({}),
    remark: text('remark'),
    channelInfo: jsonb('channel_info').$type<Record<string, unknown>>().notNull().default({}),
    testErrors: integer('test_errors').notNull().default(0),
    testAt: timestamp('test_at', { withTimezone: true }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const rateLimitRules = pgTable('rate_limit_rules', {
    id: serial('id').primaryKey(),
    name: varchar('name', { length: 100 }).notNull(),
    rpm: integer('rpm').default(0),
    rph: integer('rph').default(0),
    concurrent: integer('concurrent').default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const packages = pgTable('packages', {
    id: serial('id').primaryKey(),
    name: varchar('name', { length: 100 }).notNull(),
    subtitle: text('subtitle'),
    description: text('description'),
    price: decimal('price', { precision: 10, scale: 2 }).notNull(),
    currency: text('currency').notNull().default('USD'),
    durationDays: integer('duration_days').notNull().default(30),
    durationUnit: text('duration_unit').notNull().default('day'),
    durationValue: integer('duration_value').notNull().default(30),
    customSeconds: bigint('custom_seconds', { mode: 'number' }).notNull().default(0),
    models: jsonb('models').$type<string[]>().default([]),
    defaultRateLimitId: integer('default_rate_limit_id').references(() => rateLimitRules.id, { onDelete: 'set null' }),
    modelRateLimits: jsonb('model_rate_limits').$type<Record<string, unknown>>().default({}),
    cycleQuota: bigint('cycle_quota', { mode: 'number' }).default(0),
    cycleInterval: integer('cycle_interval').default(1),
    cycleUnit: text('cycle_unit').default('day'),
    totalAmount: bigint('total_amount', { mode: 'number' }).notNull().default(0),
    quotaResetPeriod: text('quota_reset_period').notNull().default('never'),
    quotaResetCustomSeconds: bigint('quota_reset_custom_seconds', { mode: 'number' }).notNull().default(0),
    enabled: boolean('enabled').notNull().default(true),
    isPublic: boolean('is_public').default(true),
    sortOrder: integer('sort_order').notNull().default(0),
    stripePriceId: text('stripe_price_id'),
    creemProductId: text('creem_product_id'),
    waffoPancakeProductId: text('waffo_pancake_product_id'),
    maxPurchasePerUser: integer('max_purchase_per_user').notNull().default(0),
    upgradeGroup: text('upgrade_group'),
    allowedGroups: jsonb('allowed_groups').$type<string[]>().default([]),
    addedBy: integer('added_by').references(() => users.id, { onDelete: 'set null' }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const redemptions = pgTable('redemptions', {
    id: serial('id').primaryKey(),
    name: text('name').notNull(),
    key: text('key').notNull().unique(),
    quota: bigint('quota', { mode: 'number' }).notNull().default(0),
    count: integer('count').notNull().default(1),
    usedCount: integer('used_count').notNull().default(0),
    status: integer('status').notNull().default(1),
    createdBy: integer('created_by').references(() => users.id, { onDelete: 'set null' }),
    usedBy: integer('used_by').references(() => users.id, { onDelete: 'set null' }),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const logs = pgTable('logs', {
    id: serial('id'),
    userId: integer('user_id').notNull(),
    tokenId: integer('token_id'),
    channelId: integer('channel_id'),
    modelName: text('model_name').notNull(),
    quotaCost: bigint('quota_cost', { mode: 'number' }).notNull().default(0),
    promptTokens: integer('prompt_tokens').notNull().default(0),
    completionTokens: integer('completion_tokens').notNull().default(0),
    cachedTokens: integer('cached_tokens').notNull().default(0),
    elapsedMs: integer('elapsed_ms').notNull().default(0),
    isStream: boolean('is_stream').default(false),
    errorMessage: text('error_message'),
    statusCode: integer('status_code').notNull().default(200),
    ipAddress: varchar('ip_address', { length: 45 }),
    userAgent: text('user_agent'),
    traceId: text('trace_id'),
    orgId: integer('org_id').references(() => organizations.id, { onDelete: 'set null' }),
    externalTaskId: text('external_task_id'),
    externalUserId: text('external_user_id'),
    externalWorkspaceId: text('external_workspace_id'),
    externalFeatureType: text('external_feature_type'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const modelMetadata = pgTable('model_metadata', {
    id: serial('id').primaryKey(),
    modelName: text('model_name').notNull().unique(),
    type: text('type').notNull().default('chat'),
    endpoint: text('endpoint'),
    displayName: text('display_name'),
    tags: jsonb('tags').$type<string[]>().default([]),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const tokenCache = pgTable('token_cache', {
    keyHash: text('key_hash').primaryKey(),
    tokenData: jsonb('token_data').$type<Record<string, unknown>>().notNull(),
    userId: integer('user_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
    expiredAt: timestamp('expired_at', { withTimezone: true }),
});

export const userQuotaCache = pgTable('user_quota_cache', {
    userId: integer('user_id').primaryKey(),
    quota: bigint('quota', { mode: 'number' }).notNull(),
    usedQuota: bigint('used_quota', { mode: 'number' }).notNull().default(0),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const options = pgTable('options', {
    key: text('key').primaryKey(),
    value: text('value').notNull().default(''),
});

export const vendors = pgTable('vendors', {
    id: serial('id').primaryKey(),
    name: text('name').notNull(),
    type: integer('type').default(0),
    baseUrl: text('base_url').default(''),
    logoUrl: text('logo_url').default(''),
    description: text('description').default(''),
    config: jsonb('config').$type<Record<string, unknown>>().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const tasks = pgTable('tasks', {
    id: text('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    tokenId: integer('token_id').references(() => tokens.id, { onDelete: 'set null' }),
    channelId: integer('channel_id').references(() => channels.id, { onDelete: 'set null' }),
    model: text('model').notNull(),
    type: varchar('type', { length: 50 }).notNull(),
    status: varchar('status', { length: 30 }).notNull().default('pending'),
    providerTaskId: text('provider_task_id'),
    requestBody: jsonb('request_body').$type<Record<string, unknown>>().notNull().default({}),
    result: jsonb('result').$type<Record<string, unknown>>(),
    error: text('error'),
    progress: integer('progress').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const workflowTemplates = pgTable('workflow_templates', {
    id: uuid('id').primaryKey().defaultRandom(),
    name: text('name').notNull(),
    description: text('description'),
    groupName: text('group_name').default('default'),
    templateJson: jsonb('template_json').notNull(),
    inputParameters: jsonb('input_parameters').$type<unknown[]>().notNull().default([]),
    providerType: integer('provider_type').notNull().default(100),
    userId: uuid('user_id'),
    isPublic: boolean('is_public').default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const userCheckins = pgTable('user_checkins', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    checkinDate: date('checkin_date').notNull(),
    reward: bigint('reward', { mode: 'number' }).notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});


export const healthLogs = pgTable('health_logs', {
    id: serial('id').primaryKey(),
    channelId: integer('channel_id').notNull().references(() => channels.id, { onDelete: 'cascade' }),
    status: integer('status').notNull(),
    latency: integer('latency'),
    errorMessage: text('error_message'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const dailyStats = pgTable('daily_stats', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    statDate: date('stat_date').notNull(),
    requestCount: integer('request_count').notNull().default(0),
    totalTokens: bigint('total_tokens', { mode: 'number' }).notNull().default(0),
    totalCost: bigint('total_cost', { mode: 'number' }).notNull().default(0),
    successCount: integer('success_count').notNull().default(0),
    errorCount: integer('error_count').notNull().default(0),
});

export const modelStats = pgTable('model_stats', {
    id: serial('id').primaryKey(),
    modelName: text('model_name').notNull(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    requestCount: integer('request_count').notNull().default(0),
    totalTokens: bigint('total_tokens', { mode: 'number' }).notNull().default(0),
    totalCost: bigint('total_cost', { mode: 'number' }).notNull().default(0),
    avgTokensPerRequest: integer('avg_tokens_per_request').notNull().default(0),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true }).defaultNow(),
});


export const rateLimits = pgTable('rate_limits', {
    key: text('key').primaryKey(),
    count: integer('count').notNull().default(0),
    expiredAt: timestamp('expired_at', { withTimezone: true }),
});

export const responseCache = pgTable('response_cache', {
    hash: text('hash').primaryKey(),
    modelName: text('model_name').notNull(),
    response: jsonb('response').$type<unknown>(),
    usage: jsonb('usage').$type<unknown>(),
    createdBy: integer('created_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    lastReadAt: timestamp('last_read_at', { withTimezone: true }),
    expiredAt: timestamp('expired_at', { withTimezone: true }),
});

export const agentMemories = pgTable('agent_memories', {
    id: text('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    tokenId: integer('token_id').references(() => tokens.id, { onDelete: 'cascade' }),
    orgId: integer('org_id').references(() => organizations.id, { onDelete: 'cascade' }),
    threadId: text('thread_id'),
    scope: text('scope').notNull().default('user'),
    kind: text('kind').notNull().default('fact'),
    content: text('content').notNull(),
    contentHash: text('content_hash').notNull(),
    embedding: text('embedding'),
    confidence: decimal('confidence', { precision: 5, scale: 4 }).notNull().default('1.0000'),
    sourceTraceId: text('source_trace_id'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    lastReadAt: timestamp('last_read_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const apiFiles = pgTable('api_files', {
    id: text('id').primaryKey(),
    userId: integer('user_id').notNull(),
    tokenId: integer('token_id'),
    object: text('object').default('file'),
    bytes: bigint('bytes', { mode: 'number' }).notNull().default(0),
    filename: text('filename').notNull(),
    purpose: text('purpose').notNull(),
    status: text('status').default('processed'),
    statusDetails: text('status_details'),
    content: bytea('content'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const apiBatches = pgTable('api_batches', {
    id: text('id').primaryKey(),
    userId: integer('user_id').notNull(),
    tokenId: integer('token_id'),
    endpoint: text('endpoint'),
    inputFileId: text('input_file_id'),
    completionWindow: text('completion_window').default('24h'),
    status: text('status').notNull().default('validating'),
    outputFileId: text('output_file_id'),
    errorFileId: text('error_file_id'),
    requestCounts: jsonb('request_counts').$type<{ total: number; completed: number; failed: number }>().default({ total: 0, completed: 0, failed: 0 }),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
    errors: jsonb('errors').$type<unknown[]>(),
    expiredAt: timestamp('expired_at', { withTimezone: true }),
    inProgressAt: timestamp('in_progress_at', { withTimezone: true }),
    finalizingAt: timestamp('finalizing_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    failedAt: timestamp('failed_at', { withTimezone: true }),
    cancellingAt: timestamp('cancelling_at', { withTimezone: true }),
    cancelledAt: timestamp('cancelled_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const mjTasks = pgTable('mj_tasks', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull(),
    uuid: text('uuid').notNull(),
    action: text('action').notNull(),
    prompt: text('prompt'),
    status: text('status').notNull().default('SUBMITTED'),
    progress: text('progress').default('0%'),
    imageUrl: text('image_url'),
    failReason: text('fail_reason'),
    finishTime: timestamp('finish_time', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const paymentOrders = pgTable('payment_orders', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull(),
    amount: integer('amount').notNull(),
    paymentMethod: text('payment_method').notNull(),
    orderType: text('order_type').notNull().default('topup'),
    targetType: text('target_type'),
    targetId: integer('target_id'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    status: integer('status').notNull().default(0),
    transactionId: text('transaction_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const subscriptionOrders = pgTable('subscription_orders', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    packageId: integer('package_id').notNull().references(() => packages.id, { onDelete: 'cascade' }),
    amount: integer('amount').notNull().default(0),
    currency: text('currency').notNull().default('USD'),
    money: decimal('money', { precision: 10, scale: 2 }).notNull().default('0'),
    tradeNo: text('trade_no').notNull().unique(),
    paymentMethod: text('payment_method').notNull(),
    paymentProvider: text('payment_provider').notNull().default(''),
    transactionId: text('transaction_id'),
    status: text('status').notNull().default('pending'),
    providerPayload: text('provider_payload'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const topupLogs = pgTable('topup_logs', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    paymentOrderId: integer('payment_order_id').references(() => paymentOrders.id, { onDelete: 'set null' }),
    subscriptionOrderId: integer('subscription_order_id').references(() => subscriptionOrders.id, { onDelete: 'set null' }),
    action: text('action').notNull(),
    paymentMethod: text('payment_method'),
    paymentProvider: text('payment_provider'),
    amount: bigint('amount', { mode: 'number' }).notNull().default(0),
    money: decimal('money', { precision: 10, scale: 2 }).notNull().default('0'),
    details: jsonb('details').$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const idempotencyKeys = pgTable('idempotency_keys', {
    keyHash: text('key_hash').primaryKey(),
    userId: integer('user_id').notNull(),
    responseCode: integer('response_code'),
    responseBody: jsonb('response_body').$type<unknown>(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
});

export const logDetails = pgTable('log_details', {
    logId: integer('log_id').primaryKey(),
    logCreatedAt: timestamp('log_created_at', { withTimezone: true }),
    requestBody: text('request_body'),
    responseBody: text('response_body'),
});

export const budgetAlerts = pgTable('budget_alerts', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull(),
    username: text('username').notNull(),
    quota: bigint('quota', { mode: 'number' }).notNull(),
    usedQuota: bigint('used_quota', { mode: 'number' }).notNull(),
    usagePercent: decimal('usage_percent', { precision: 5, scale: 4 }).notNull(),
    alertLevel: text('alert_level').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const auditLogs = pgTable('audit_logs', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull(),
    username: text('username').notNull(),
    action: text('action').notNull(),
    resource: text('resource').notNull(),
    resourceId: text('resource_id'),
    details: jsonb('details').$type<Record<string, unknown>>(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const userSubscriptions = pgTable('user_subscriptions', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    packageId: integer('package_id').notNull().references(() => packages.id, { onDelete: 'cascade' }),
    status: integer('status').notNull().default(1),
    source: text('source').notNull().default('order'),
    startTime: timestamp('start_time', { withTimezone: true }).defaultNow(),
    endTime: timestamp('end_time', { withTimezone: true }).notNull(),
    amountTotal: bigint('amount_total', { mode: 'number' }).notNull().default(0),
    amountUsed: bigint('amount_used', { mode: 'number' }).notNull().default(0),
    quotaGranted: bigint('quota_granted', { mode: 'number' }).default(0),
    quotaUsed: bigint('quota_used', { mode: 'number' }).default(0),
    lastResetAt: timestamp('last_reset_at', { withTimezone: true }).defaultNow(),
    nextResetAt: timestamp('next_reset_at', { withTimezone: true }),
    upgradeGroup: text('upgrade_group'),
    prevUserGroup: text('prev_user_group'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const inviteCodes = pgTable('invite_codes', {
    id: serial('id').primaryKey(),
    code: text('code').notNull().unique(),
    maxUses: integer('max_uses').notNull().default(1),
    usedCount: integer('used_count').notNull().default(0),
    giftQuota: bigint('gift_quota', { mode: 'number' }).notNull().default(0),
    status: integer('status').notNull().default(1),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    createdBy: integer('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const announcements = pgTable('announcements', {
    id: serial('id').primaryKey(),
    title: text('title').notNull(),
    content: text('content').notNull().default(''),
    tag: text('tag'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const userAff = pgTable('user_aff', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull().unique().references(() => users.id, { onDelete: 'cascade' }),
    code: text('code').notNull().unique(),
    reward: bigint('reward', { mode: 'number' }).notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const userAffRewards = pgTable('user_aff_rewards', {
    id: serial('id').primaryKey(),
    referrerId: integer('referrer_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    refereeId: integer('referee_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    reward: bigint('reward', { mode: 'number' }).notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});


export const oauthAccounts = pgTable('oauth_accounts', {
    id: serial('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    provider: text('provider').notNull(),
    providerUserId: text('provider_user_id').notNull(),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const customOAuthProviders = pgTable('custom_oauth_providers', {
    id: serial('id').primaryKey(),
    name: text('name').notNull(),
    issuer: text('issuer'),
    discoveryUrl: text('discovery_url'),
    clientId: text('client_id'),
    clientSecret: text('client_secret'),
    authorizationEndpoint: text('authorization_endpoint'),
    tokenEndpoint: text('token_endpoint'),
    userinfoEndpoint: text('userinfo_endpoint'),
    jwksUri: text('jwks_uri'),
    scopes: jsonb('scopes').$type<string[]>().default([]),
    enabled: boolean('enabled').notNull().default(true),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const verificationCodes = pgTable('verification_codes', {
    id: serial('id').primaryKey(),
    type: text('type').notNull(),
    target: text('target').notNull(),
    code: text('code').notNull(),
    userId: integer('user_id').references(() => users.id, { onDelete: 'cascade' }),
    ipAddress: text('ip_address'),
    consumed: boolean('consumed').notNull().default(false),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});


// ─── Assistants / Threads / Vector Stores ─────────────────────────────────
export const assistants = pgTable('assistants', {
    id: text('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    tokenId: integer('token_id'),
    object: text('object').default('assistant'),
    name: text('name'),
    description: text('description'),
    model: text('model').notNull(),
    instructions: text('instructions'),
    tools: jsonb('tools').$type<Record<string, any>[]>().default([]),
    fileIds: jsonb('file_ids').$type<string[]>().default([]),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
    temperature: decimal('temperature', { precision: 5, scale: 2 }),
    topP: decimal('top_p', { precision: 5, scale: 4 }),
    status: text('status').default('active'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const threads = pgTable('threads', {
    id: text('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    tokenId: integer('token_id'),
    object: text('object').default('thread'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
    toolResources: jsonb('tool_resources').$type<Record<string, unknown>>().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const threadMessages = pgTable('thread_messages', {
    id: text('id').primaryKey(),
    threadId: text('thread_id').notNull().references(() => threads.id, { onDelete: 'cascade' }),
    userId: integer('user_id').notNull(),
    object: text('object').default('thread.message'),
    role: text('role').notNull().default('user'),
    content: jsonb('content').$type<Record<string, any>[]>().default([]),
    assistantId: text('assistant_id'),
    runId: text('run_id'),
    attachments: jsonb('attachments').$type<Record<string, any>[]>().default([]),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const threadRuns = pgTable('thread_runs', {
    id: text('id').primaryKey(),
    threadId: text('thread_id').notNull().references(() => threads.id, { onDelete: 'cascade' }),
    assistantId: text('assistant_id'),
    userId: integer('user_id').notNull(),
    object: text('object').default('thread.run'),
    status: text('status').notNull().default('queued'),
    model: text('model'),
    instructions: text('instructions'),
    tools: jsonb('tools').$type<Record<string, any>[]>().default([]),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
    temperature: decimal('temperature', { precision: 5, scale: 2 }),
    topP: decimal('top_p', { precision: 5, scale: 4 }),
    maxPromptTokens: integer('max_prompt_tokens'),
    maxCompletionTokens: integer('max_completion_tokens'),
    truncationStrategy: jsonb('truncation_strategy').$type<Record<string, unknown>>(),
    toolChoice: jsonb('tool_choice'),
    responseFormat: jsonb('response_format'),
    requiredAction: jsonb('required_action').$type<Record<string, unknown>>(),
    lastError: jsonb('last_error').$type<Record<string, unknown>>(),
    usage: jsonb('usage').$type<Record<string, unknown>>(),
    startedAt: timestamp('started_at', { withTimezone: true }),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    cancelledAt: timestamp('cancelled_at', { withTimezone: true }),
    failedAt: timestamp('failed_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const vectorStores = pgTable('vector_stores', {
    id: text('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    tokenId: integer('token_id'),
    object: text('object').default('vector_store'),
    name: text('name'),
    fileCounts: jsonb('file_counts').$type<Record<string, number>>().default({ in_progress: 0, completed: 0, failed: 0, cancelled: 0, total: 0 }),
    status: text('status').default('completed'),
    usageBytes: bigint('usage_bytes', { mode: 'number' }).notNull().default(0),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}),
    expiresAfter: jsonb('expires_after').$type<Record<string, unknown>>(),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    lastActiveAt: timestamp('last_active_at', { withTimezone: true }).defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const vectorStoreFiles = pgTable('vector_store_files', {
    id: text('id').primaryKey(),
    vectorStoreId: text('vector_store_id').notNull().references(() => vectorStores.id, { onDelete: 'cascade' }),
    fileId: text('file_id'),
    object: text('object').default('vector_store.file'),
    status: text('status').default('completed'),
    usageBytes: bigint('usage_bytes', { mode: 'number' }).notNull().default(0),
    lastError: jsonb('last_error').$type<Record<string, unknown>>(),
    chunkingStrategy: jsonb('chunking_strategy').$type<Record<string, unknown>>(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const fineTuningJobs = pgTable('fine_tuning_jobs', {
    id: text('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    tokenId: integer('token_id'),
    object: text('object').default('fine_tuning.job'),
    model: text('model').notNull(),
    trainingFileId: text('training_file'),
    validationFileId: text('validation_file'),
    hyperparameters: jsonb('hyperparameters').$type<Record<string, unknown>>().default({}),
    status: text('status').notNull().default('validating_files'),
    fineTunedModel: text('fine_tuned_model'),
    organizationId: text('organization_id'),
    resultFiles: jsonb('result_files').$type<string[]>().default([]),
    trainedTokens: integer('trained_tokens'),
    error: jsonb('error').$type<Record<string, unknown>>(),
    epochs: integer('epochs'),
    suffix: text('suffix'),
    integrations: jsonb('integrations').$type<Record<string, unknown>[]>().default([]),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    finishedAt: timestamp('finished_at', { withTimezone: true }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const loginAttempts = pgTable('login_attempts', {
    id: serial('id').primaryKey(),
    username: text('username').notNull(),
    ipAddress: text('ip_address'),
    success: boolean('success').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const twoFactorLoginChallenges = pgTable('two_factor_login_challenges', {
    id: text('id').primaryKey(),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});


// ─── Enterprise Team / Project / Member ──────────────────────

export const teams = pgTable('teams', {
    id: serial('id').primaryKey(),
    orgId: integer('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 120 }).notNull(),
    slug: varchar('slug', { length: 80 }),
    description: text('description'),
    leaderId: integer('leader_id').references(() => users.id, { onDelete: 'set null' }),
    budget: bigint('budget', { mode: 'number' }).notNull().default(0),
    usedBudget: bigint('used_budget', { mode: 'number' }).notNull().default(0),
    allowedModels: jsonb('allowed_models').$type<string[]>().notNull().default([]),
    deniedModels: jsonb('denied_models').$type<string[]>().notNull().default([]),
    status: integer('status').notNull().default(1),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const projects = pgTable('projects', {
    id: serial('id').primaryKey(),
    orgId: integer('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    teamId: integer('team_id').references(() => teams.id, { onDelete: 'set null' }),
    name: varchar('name', { length: 120 }).notNull(),
    slug: varchar('slug', { length: 80 }),
    description: text('description'),
    budget: bigint('budget', { mode: 'number' }).notNull().default(0),
    usedBudget: bigint('used_budget', { mode: 'number' }).notNull().default(0),
    allowedModels: jsonb('allowed_models').$type<string[]>().notNull().default([]),
    deniedModels: jsonb('denied_models').$type<string[]>().notNull().default([]),
    status: integer('status').notNull().default(1),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const teamMembers = pgTable('team_members', {
    id: serial('id').primaryKey(),
    teamId: integer('team_id').notNull().references(() => teams.id, { onDelete: 'cascade' }),
    userId: integer('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    role: varchar('role', { length: 30 }).notNull().default('member'),
    joinedAt: timestamp('joined_at', { withTimezone: true }).defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

// ─── Elygate Enterprise Control Plane Projections ─────────────

export const enterpriseGatewayInstances = pgTable('enterprise_gateway_instances', {
    id: serial('id').primaryKey(),
    tenantId: text('tenant_id').notNull(),
    orgId: text('org_id').notNull(),
    appId: text('app_id').notNull(),
    appInstanceId: text('app_instance_id').notNull(),
    projectId: text('project_id'),
    status: varchar('status', { length: 30 }).notNull().default('provisioning'),
    publicBaseUrl: text('public_base_url'),
    adminBaseUrl: text('admin_base_url'),
    databaseUrlSecretName: text('database_url_secret_name'),
    supauthIssuerUrl: text('supauth_issuer_url'),
    supauthJwksUrl: text('supauth_jwks_url'),
    supauthAudience: text('supauth_audience'),
    entitlementsVersion: integer('entitlements_version').notNull().default(0),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const enterpriseIdentityPolicies = pgTable('enterprise_identity_policies', {
    id: serial('id').primaryKey(),
    tenantId: text('tenant_id').notNull(),
    orgId: text('org_id').notNull(),
    appInstanceId: text('app_instance_id').notNull(),
    name: text('name').notNull(),
    targetKind: varchar('target_kind', { length: 40 }).notNull().default('org'),
    targetId: text('target_id'),
    effect: varchar('effect', { length: 20 }).notNull().default('allow'),
    rules: jsonb('rules').$type<Record<string, unknown>>().notNull().default({}),
    status: varchar('status', { length: 30 }).notNull().default('active'),
    createdBy: text('created_by'),
    updatedBy: text('updated_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const enterpriseBudgets = pgTable('enterprise_budgets', {
    id: serial('id').primaryKey(),
    tenantId: text('tenant_id').notNull(),
    orgId: text('org_id').notNull(),
    appInstanceId: text('app_instance_id').notNull(),
    subjectKind: varchar('subject_kind', { length: 40 }).notNull().default('org'),
    subjectId: text('subject_id'),
    period: varchar('period', { length: 30 }).notNull().default('monthly'),
    limitQuota: bigint('limit_quota', { mode: 'number' }).notNull().default(0),
    usedQuota: bigint('used_quota', { mode: 'number' }).notNull().default(0),
    alertThresholdPct: integer('alert_threshold_pct').notNull().default(80),
    resetAt: timestamp('reset_at', { withTimezone: true }),
    status: varchar('status', { length: 30 }).notNull().default('active'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    createdBy: text('created_by'),
    updatedBy: text('updated_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const enterpriseAuditEvents = pgTable('enterprise_audit_events', {
    id: serial('id').primaryKey(),
    tenantId: text('tenant_id').notNull(),
    orgId: text('org_id').notNull(),
    appInstanceId: text('app_instance_id').notNull(),
    actorType: varchar('actor_type', { length: 40 }).notNull().default('user'),
    actorId: text('actor_id'),
    action: text('action').notNull(),
    resource: text('resource').notNull(),
    resourceId: text('resource_id'),
    details: jsonb('details').$type<Record<string, unknown>>().notNull().default({}),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const enterpriseOrgEntitlements = pgTable('enterprise_org_entitlements', {
    id: serial('id').primaryKey(),
    tenantId: text('tenant_id').notNull(),
    orgId: text('org_id').notNull(),
    appInstanceId: text('app_instance_id').notNull(),
    seatLimit: integer('seat_limit').notNull().default(5),
    assignedSeats: integer('assigned_seats').notNull().default(0),
    billingMode: varchar('billing_mode', { length: 30 }).notNull().default('prepaid'),
    overageEnabled: boolean('overage_enabled').notNull().default(false),
    overageUnitPriceCents: integer('overage_unit_price_cents').notNull().default(0),
    budgetMode: varchar('budget_mode', { length: 30 }).notNull().default('hard_limit'),
    defaultNoTraining: boolean('default_no_training').notNull().default(true),
    dataRetentionDays: integer('data_retention_days').notNull().default(30),
    providerComplianceMode: varchar('provider_compliance_mode', { length: 30 }).notNull().default('strict'),
    allowedIpPolicy: text('allowed_ip_policy'),
    status: varchar('status', { length: 30 }).notNull().default('active'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    createdBy: text('created_by'),
    updatedBy: text('updated_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const enterpriseMemberships = pgTable('enterprise_memberships', {
    id: serial('id').primaryKey(),
    tenantId: text('tenant_id').notNull(),
    orgId: text('org_id').notNull(),
    appInstanceId: text('app_instance_id').notNull(),
    userId: text('user_id'),
    email: text('email'),
    displayName: text('display_name'),
    role: varchar('role', { length: 40 }).notNull().default('developer'),
    scopes: jsonb('scopes').$type<string[]>().notNull().default([]),
    seatKind: varchar('seat_kind', { length: 30 }).notNull().default('human'),
    seatStatus: varchar('seat_status', { length: 30 }).notNull().default('active'),
    invitedBy: text('invited_by'),
    joinedAt: timestamp('joined_at', { withTimezone: true }),
    lastActiveAt: timestamp('last_active_at', { withTimezone: true }),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const enterpriseBillingAccounts = pgTable('enterprise_billing_accounts', {
    id: serial('id').primaryKey(),
    tenantId: text('tenant_id').notNull(),
    orgId: text('org_id').notNull(),
    appInstanceId: text('app_instance_id').notNull(),
    billingName: text('billing_name').notNull(),
    billingEmail: text('billing_email'),
    taxId: text('tax_id'),
    currency: text('currency').notNull().default('USD'),
    paymentTerms: varchar('payment_terms', { length: 40 }).notNull().default('net_30'),
    status: varchar('status', { length: 30 }).notNull().default('active'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    createdBy: text('created_by'),
    updatedBy: text('updated_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const enterpriseInvoices = pgTable('enterprise_invoices', {
    id: serial('id').primaryKey(),
    tenantId: text('tenant_id').notNull(),
    orgId: text('org_id').notNull(),
    appInstanceId: text('app_instance_id').notNull(),
    billingAccountId: integer('billing_account_id').references(() => enterpriseBillingAccounts.id, { onDelete: 'set null' }),
    invoiceNumber: text('invoice_number').notNull(),
    periodStart: timestamp('period_start', { withTimezone: true }).notNull(),
    periodEnd: timestamp('period_end', { withTimezone: true }).notNull(),
    currency: text('currency').notNull().default('USD'),
    subtotalCents: bigint('subtotal_cents', { mode: 'number' }).notNull().default(0),
    taxCents: bigint('tax_cents', { mode: 'number' }).notNull().default(0),
    totalCents: bigint('total_cents', { mode: 'number' }).notNull().default(0),
    status: varchar('status', { length: 30 }).notNull().default('draft'),
    dueAt: timestamp('due_at', { withTimezone: true }),
    issuedAt: timestamp('issued_at', { withTimezone: true }),
    paidAt: timestamp('paid_at', { withTimezone: true }),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const enterpriseInvoiceItems = pgTable('enterprise_invoice_items', {
    id: serial('id').primaryKey(),
    invoiceId: integer('invoice_id').notNull().references(() => enterpriseInvoices.id, { onDelete: 'cascade' }),
    itemType: varchar('item_type', { length: 40 }).notNull(),
    description: text('description').notNull(),
    quantity: decimal('quantity', { precision: 20, scale: 4 }).notNull().default('1'),
    unitAmountCents: bigint('unit_amount_cents', { mode: 'number' }).notNull().default(0),
    amountCents: bigint('amount_cents', { mode: 'number' }).notNull().default(0),
    sourceType: varchar('source_type', { length: 40 }),
    sourceId: text('source_id'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const enterpriseMeteredUsage = pgTable('enterprise_metered_usage', {
    id: serial('id').primaryKey(),
    tenantId: text('tenant_id').notNull(),
    orgId: text('org_id').notNull(),
    appInstanceId: text('app_instance_id').notNull(),
    subjectKind: varchar('subject_kind', { length: 40 }).notNull().default('org'),
    subjectId: text('subject_id'),
    metric: varchar('metric', { length: 40 }).notNull().default('quota'),
    quantity: bigint('quantity', { mode: 'number' }).notNull().default(0),
    unitAmountCents: integer('unit_amount_cents').notNull().default(0),
    amountCents: bigint('amount_cents', { mode: 'number' }).notNull().default(0),
    sourceLogId: integer('source_log_id'),
    invoiceId: integer('invoice_id').references(() => enterpriseInvoices.id, { onDelete: 'set null' }),
    occurredAt: timestamp('occurred_at', { withTimezone: true }).defaultNow(),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const enterpriseProviderCompliance = pgTable('enterprise_provider_compliance', {
    id: serial('id').primaryKey(),
    tenantId: text('tenant_id').notNull(),
    orgId: text('org_id').notNull(),
    appInstanceId: text('app_instance_id').notNull(),
    providerKind: varchar('provider_kind', { length: 60 }).notNull(),
    providerId: text('provider_id').notNull(),
    displayName: text('display_name'),
    noTraining: boolean('no_training').notNull().default(false),
    zeroRetention: boolean('zero_retention').notNull().default(false),
    region: text('region'),
    status: varchar('status', { length: 30 }).notNull().default('review'),
    evidenceUrl: text('evidence_url'),
    reviewedBy: text('reviewed_by'),
    reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

// ─── Soft-Delete Recovery (recycle bin) ──────────────────────

export const deletedRecords = pgTable('deleted_records', {
    id: serial('id').primaryKey(),
    resourceType: varchar('resource_type', { length: 60 }).notNull(),
    resourceId: integer('resource_id').notNull(),
    snapshot: jsonb('snapshot').$type<Record<string, unknown>>().notNull(),
    deletedBy: integer('deleted_by').references(() => users.id, { onDelete: 'set null' }),
    restoredAt: timestamp('restored_at', { withTimezone: true }),
    restoredBy: integer('restored_by').references(() => users.id, { onDelete: 'set null' }),
    purgeAt: timestamp('purge_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const schema = {
    channels,
    logs,
    'models-meta': modelMetadata,
    options,
    organizations,
    packages,
    'rate-limits': rateLimitRules,
    redemptions,
    sessions,
    'token-cache': tokenCache,
    tasks,
    tokens,
    'user-checkins': userCheckins,
    'user-groups': userGroups,
    'user-quota-cache': userQuotaCache,
    users,
    vendors,
    'workflow-templates': workflowTemplates,
    'health-logs': healthLogs,
    'daily-stats': dailyStats,
    'model-stats': modelStats,
    'rate-limits-table': rateLimits,
    'response-cache': responseCache,
    'agent-memories': agentMemories,
    'api-files': apiFiles,
    'api-batches': apiBatches,
    'mj-tasks': mjTasks,
    'payment-orders': paymentOrders,
    'subscription-orders': subscriptionOrders,
    'topup-logs': topupLogs,
    'idempotency-keys': idempotencyKeys,
    'log-details': logDetails,
    'budget-alerts': budgetAlerts,
    'audit-logs': auditLogs,
    'user-subscriptions': userSubscriptions,
    'invite-codes': inviteCodes,
    announcements,
    'user-aff': userAff,
    'user-aff-rewards': userAffRewards,
    oauthAccounts,
    'custom-oauth-providers': customOAuthProviders,
    assistants,
    threads,
    'thread-messages': threadMessages,
    'thread-runs': threadRuns,
    'vector-stores': vectorStores,
    'vector-store-files': vectorStoreFiles,
    'fine-tuning-jobs': fineTuningJobs,
    'verification-codes': verificationCodes,
    loginAttempts,
    'two-factor-login-challenges': twoFactorLoginChallenges,
    teams,
    projects,
    'team-members': teamMembers,
    'enterprise-gateway-instances': enterpriseGatewayInstances,
    'enterprise-identity-policies': enterpriseIdentityPolicies,
    'enterprise-budgets': enterpriseBudgets,
    'enterprise-audit-events': enterpriseAuditEvents,
    'enterprise-org-entitlements': enterpriseOrgEntitlements,
    'enterprise-memberships': enterpriseMemberships,
    'enterprise-billing-accounts': enterpriseBillingAccounts,
    'enterprise-invoices': enterpriseInvoices,
    'enterprise-invoice-items': enterpriseInvoiceItems,
    'enterprise-metered-usage': enterpriseMeteredUsage,
    'enterprise-provider-compliance': enterpriseProviderCompliance,
    'deleted-records': deletedRecords,
};

export type DatabaseSchema = typeof schema;
