import type { ResourceDefinition } from '@svadmin/core';

export const enterpriseResources: ResourceDefinition[] = [
  {
    name: 'enterprise-overview',
    label: '企业总览',
    icon: 'layout-dashboard',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    fields: [],
  },
  {
    name: 'gateway-instances',
    label: '网关实例',
    icon: 'server',
    canCreate: false,
    canEdit: true,
    canDelete: false,
    canShow: false,
    primaryKey: 'id',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'app_instance_id', label: 'App Instance', type: 'text', showInForm: false },
      { key: 'tenant_id', label: 'Tenant', type: 'text', showInForm: false },
      { key: 'org_id', label: 'Org', type: 'text', showInForm: false },
      { key: 'project_id', label: 'Project', type: 'text' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: 'provisioning', value: 'provisioning' },
        { label: 'active', value: 'active' },
        { label: 'suspended', value: 'suspended' },
        { label: 'deleted', value: 'deleted' },
      ] },
      { key: 'public_base_url', label: 'Public URL', type: 'url' },
      { key: 'admin_base_url', label: 'Admin URL', type: 'url' },
      { key: 'entitlements_version', label: 'Entitlements', type: 'number' },
      { key: 'updated_at', label: '更新时间', type: 'date', showInForm: false },
    ],
  },
  {
    name: 'gateway-resources',
    label: '网关资源',
    icon: 'network',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    fields: [],
  },
  {
    name: 'provider-channels',
    label: '供应商渠道',
    icon: 'network',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    primaryKey: 'id',
    fields: [
      { key: 'id', label: 'ID', type: 'number', width: '72px' },
      { key: 'name', label: '渠道名', type: 'text', searchable: true },
      { key: 'type', label: '类型', type: 'number' },
      { key: 'endpoint_type', label: 'Endpoint', type: 'text' },
      { key: 'models', label: 'Models', type: 'textarea' },
      { key: 'groups', label: 'Groups', type: 'textarea' },
      { key: 'credential_mask', label: 'Key', type: 'text' },
      { key: 'status', label: '状态', type: 'number' },
      { key: 'price_ratio', label: '成本倍率', type: 'number' },
      { key: 'updated_at', label: '更新时间', type: 'date' },
    ],
  },
  {
    name: 'model-routes',
    label: '模型路由',
    icon: 'route',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    primaryKey: 'id',
    fields: [
      { key: 'id', label: 'ID', type: 'text' },
      { key: 'model_name', label: '模型', type: 'text', searchable: true },
      { key: 'channel_name', label: '渠道', type: 'text' },
      { key: 'mapped_model', label: 'Mapped', type: 'text' },
      { key: 'priority', label: '优先级', type: 'number' },
      { key: 'weight', label: '权重', type: 'number' },
      { key: 'groups', label: 'Groups', type: 'textarea' },
      { key: 'status', label: '状态', type: 'number' },
    ],
  },
  {
    name: 'gateway-api-keys',
    label: '数据面 Key',
    icon: 'key-round',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    primaryKey: 'id',
    fields: [
      { key: 'id', label: 'ID', type: 'number', width: '72px' },
      { key: 'name', label: '名称', type: 'text', searchable: true },
      { key: 'username', label: '用户', type: 'text' },
      { key: 'key_mask', label: 'Key', type: 'text' },
      { key: 'status', label: '状态', type: 'number' },
      { key: 'remain_quota', label: '剩余额度', type: 'number' },
      { key: 'used_quota', label: '已用额度', type: 'number' },
      { key: 'rate_limit', label: '限流', type: 'number' },
      { key: 'accessed_at', label: '访问时间', type: 'date' },
    ],
  },
  {
    name: 'request-logs',
    label: '请求日志',
    icon: 'activity',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    primaryKey: 'id',
    fields: [
      { key: 'id', label: 'ID', type: 'number', width: '72px' },
      { key: 'created_at', label: '时间', type: 'date' },
      { key: 'model_name', label: '模型', type: 'text', searchable: true },
      { key: 'status_code', label: '状态', type: 'number' },
      { key: 'quota_cost', label: '成本', type: 'number' },
      { key: 'prompt_tokens', label: 'Prompt', type: 'number' },
      { key: 'completion_tokens', label: 'Completion', type: 'number' },
      { key: 'elapsed_ms', label: '耗时', type: 'number' },
      { key: 'trace_id', label: 'Trace', type: 'text' },
    ],
  },
  {
    name: 'agent-memories',
    label: 'Agent Memory',
    icon: 'brain',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    primaryKey: 'id',
    fields: [
      { key: 'id', label: 'ID', type: 'text' },
      { key: 'user_id', label: 'User', type: 'number' },
      { key: 'scope', label: 'Scope', type: 'text' },
      { key: 'kind', label: 'Kind', type: 'text' },
      { key: 'content_preview', label: 'Content', type: 'textarea' },
      { key: 'content_length', label: '长度', type: 'number' },
      { key: 'confidence', label: '置信度', type: 'number' },
      { key: 'last_read_at', label: '最近读取', type: 'date' },
    ],
  },
  {
    name: 'identity-and-policy',
    label: '身份与策略',
    icon: 'shield',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    fields: [],
  },
  {
    name: 'identity-policies',
    label: '企业策略',
    icon: 'shield-check',
    canCreate: true,
    canEdit: true,
    canDelete: false,
    canShow: false,
    primaryKey: 'id',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: '策略名', type: 'text', required: true, searchable: true },
      { key: 'target_kind', label: 'Target', type: 'select', options: [
        { label: 'org', value: 'org' },
        { label: 'tenant', value: 'tenant' },
        { label: 'app_instance', value: 'app_instance' },
        { label: 'project', value: 'project' },
        { label: 'user', value: 'user' },
        { label: 'service_account', value: 'service_account' },
        { label: 'api_key', value: 'api_key' },
        { label: 'model', value: 'model' },
        { label: 'channel', value: 'channel' },
        { label: 'external_user', value: 'external_user' },
        { label: 'external_workspace', value: 'external_workspace' },
        { label: 'feature', value: 'feature' },
      ] },
      { key: 'target_id', label: 'Target ID', type: 'text' },
      { key: 'effect', label: 'Effect', type: 'select', options: [
        { label: 'allow', value: 'allow' },
        { label: 'deny', value: 'deny' },
      ] },
      { key: 'rules', label: 'Rules', type: 'textarea' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: 'active', value: 'active' },
        { label: 'suspended', value: 'suspended' },
      ] },
      { key: 'updated_at', label: '更新时间', type: 'date', showInForm: false },
    ],
  },
  {
    name: 'usage-and-budget',
    label: '用量与预算',
    icon: 'chart-no-axes-combined',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    fields: [],
  },
  {
    name: 'budgets',
    label: '企业预算',
    icon: 'wallet',
    canCreate: true,
    canEdit: true,
    canDelete: false,
    canShow: false,
    primaryKey: 'id',
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'subject_kind', label: 'Subject', type: 'select', options: [
        { label: 'org', value: 'org' },
        { label: 'project', value: 'project' },
        { label: 'user', value: 'user' },
        { label: 'service_account', value: 'service_account' },
        { label: 'api_key', value: 'api_key' },
        { label: 'external_workspace', value: 'external_workspace' },
        { label: 'feature', value: 'feature' },
      ] },
      { key: 'subject_id', label: 'Subject ID', type: 'text' },
      { key: 'period', label: '周期', type: 'select', options: [
        { label: 'daily', value: 'daily' },
        { label: 'monthly', value: 'monthly' },
        { label: 'quarterly', value: 'quarterly' },
      ] },
      { key: 'limit_quota', label: '预算额度', type: 'number', required: true },
      { key: 'used_quota', label: '已用额度', type: 'number' },
      { key: 'alert_threshold_pct', label: '告警阈值', type: 'number' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: 'active', value: 'active' },
        { label: 'suspended', value: 'suspended' },
      ] },
      { key: 'reset_at', label: '重置时间', type: 'date' },
    ],
  },
  {
    name: 'audit-events',
    label: '审计事件',
    icon: 'scroll-text',
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canShow: false,
    primaryKey: 'id',
    fields: [
      { key: 'id', label: 'ID', type: 'number', width: '72px' },
      { key: 'created_at', label: '时间', type: 'date' },
      { key: 'actor_type', label: 'Actor Type', type: 'text' },
      { key: 'actor_id', label: 'Actor', type: 'text' },
      { key: 'action', label: 'Action', type: 'text', searchable: true },
      { key: 'resource', label: 'Resource', type: 'text' },
      { key: 'resource_id', label: 'Resource ID', type: 'text' },
      { key: 'details', label: 'Details', type: 'textarea' },
    ],
  },
];
