import type { ElygateLocale } from './i18n';

const columnTranslations: Record<ElygateLocale, Record<string, string>> = {
	'zh-CN': {
		id: 'ID',
		request_id: '请求 ID',
		provider: '供应商',
		name: '名称',
		description: '描述',
		model: '模型',
		timestamp: '时间',
		status: '状态',
		status_code: '状态码',
		method: '方法',
		path: '路径',
		content: '内容',
		latency: '延迟',
		duration: '耗时',
		prompt_tokens: '输入 Token',
		completion_tokens: '输出 Token',
		total_tokens: '总 Token',
		cost: '成本',
		customer_id: '客户 ID',
		calendar_aligned: '日历重置',
		budgets: '预算',
		rate_limit: '限流',
		enabled: '启用',
		scope: '范围',
		scope_id: '范围 ID',
		priority: '优先级',
		cel_expression: 'CEL 表达式',
		targets: '目标',
		model_name: '模型名称',
		virtual_key_id: '虚拟密钥 ID',
		provider_id: '供应商 ID',
		provider_key_id: '密钥 ID',
		scope_kind: '范围类型',
		match_type: '匹配方式',
		pattern: '匹配模式',
		request_types: '请求类型',
		url: 'URL',
		events: '事件',
		disabled: '停用',
		include_response: '包含响应',
		failure_count: '失败次数',
		kind: '类型',
		auth_kind: '认证类型',
		auth_mode: '认证模式',
		user_id: '用户 ID',
		virtual_key: '虚拟密钥',
		mcp_client: 'MCP 客户端',
		server_label: '服务标签',
		tool_name: '工具',
		actualName: '实际名称',
		isCustom: '自定义',
		version: '版本',
		license: '许可证',
		compatibility: '兼容性',
		folder_id: '目录 ID',
		created_at: '创建时间',
		updated_at: '更新时间',
		expires_at: '过期时间',
		max_limit: '上限',
		current_usage: '当前用量',
		reset_duration: '重置周期',
		last_reset: '上次重置',
		token_max_limit: 'Token 上限',
		token_current_usage: 'Token 用量',
		request_max_limit: '请求上限',
		request_current_usage: '请求用量',
	},
	en: {
		id: 'ID',
		request_id: 'Request ID',
		provider: 'Provider',
		name: 'Name',
		description: 'Description',
		model: 'Model',
		timestamp: 'Timestamp',
		status: 'Status',
		status_code: 'Status code',
		method: 'Method',
		path: 'Path',
		content: 'Content',
		latency: 'Latency',
		duration: 'Duration',
		prompt_tokens: 'Input tokens',
		completion_tokens: 'Output tokens',
		total_tokens: 'Total tokens',
		cost: 'Cost',
		customer_id: 'Customer ID',
		calendar_aligned: 'Calendar aligned',
		budgets: 'Budgets',
		rate_limit: 'Rate limit',
		enabled: 'Enabled',
		scope: 'Scope',
		scope_id: 'Scope ID',
		priority: 'Priority',
		cel_expression: 'CEL expression',
		targets: 'Targets',
		model_name: 'Model name',
		virtual_key_id: 'Virtual key ID',
		provider_id: 'Provider ID',
		provider_key_id: 'Key ID',
		scope_kind: 'Scope kind',
		match_type: 'Match type',
		pattern: 'Pattern',
		request_types: 'Request types',
		url: 'URL',
		events: 'Events',
		disabled: 'Disabled',
		include_response: 'Include response',
		failure_count: 'Failures',
		kind: 'Kind',
		auth_kind: 'Auth kind',
		auth_mode: 'Auth mode',
		user_id: 'User ID',
		virtual_key: 'Virtual key',
		mcp_client: 'MCP client',
		server_label: 'Server label',
		tool_name: 'Tool',
		actualName: 'Actual name',
		isCustom: 'Custom',
		version: 'Version',
		license: 'License',
		compatibility: 'Compatibility',
		folder_id: 'Folder ID',
		created_at: 'Created at',
		updated_at: 'Updated at',
		expires_at: 'Expires at',
		max_limit: 'Max limit',
		current_usage: 'Current usage',
		reset_duration: 'Reset duration',
		last_reset: 'Last reset',
		token_max_limit: 'Token max',
		token_current_usage: 'Token usage',
		request_max_limit: 'Request max',
		request_current_usage: 'Request usage',
	},
};

export function columnLabelFor(locale: ElygateLocale, column: string): string {
	const translated = columnTranslations[locale][column];
	if (translated) return translated;
	if (locale === 'zh-CN') return column;
	const words = column.replace(/[_-]+/g, ' ').trim();
	return words ? words.charAt(0).toUpperCase() + words.slice(1) : column;
}
