package bedrock

import (
	"context"
	"fmt"
	"testing"

	"github.com/maximhq/bifrost/core/schemas"
	"github.com/stretchr/testify/require"
)

// Regression tests for maximhq/bifrost#6624.
//
// Bedrock Converse's ReasoningTextBlock documents signature as optional
// (https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_ReasoningTextBlock.html),
// and Nova / MiniMax reject the field when it is present but empty. Claude is
// the opposite: every thinking block it is handed back must carry the
// signature it issued, because the signature is the encrypted thinking the
// server verifies ("The API uses the signature to verify that thinking blocks
// were generated by Claude when you pass them back",
// https://platform.claude.com/docs/en/build-with-claude/thinking#thinking-encryption).
//
// Probed live against global.anthropic.claude-sonnet-4-6 on Converse on
// 2026-09-07, a thinking block with no signature is rejected in every
// serialisation: the field absent gives "thinking.signature: Field required",
// and the field present but empty gives "each thinking block must contain
// thinking" (empty text) or "Invalid `signature` in `thinking` block" (prose).
// So there is no wire shape that makes an unsigned block acceptable to Claude;
// the block has to be left out of the replay for Anthropic-family models,
// while Nova keeps receiving it exactly as today.

const (
	unsignedReasoningClaude = "global.anthropic.claude-sonnet-4-6"
	unsignedReasoningNova   = "amazon.nova-pro-v1:0"
)

func reasoningBlocksInConverse(msgs []BedrockMessage) []BedrockContentBlock {
	var out []BedrockContentBlock
	for _, m := range msgs {
		for _, b := range m.Content {
			if b.ReasoningContent != nil {
				out = append(out, b)
			}
		}
	}
	return out
}

func responsesReplayWithReasoning(model string, reasoning *schemas.ResponsesMessage) *schemas.BifrostResponsesRequest {
	user := schemas.ResponsesInputMessageRoleUser
	assistant := schemas.ResponsesInputMessageRoleAssistant
	q := "hello"
	a := "hi there"
	q2 := "Reply with just the word ok."
	reasoning.Role = &assistant
	return &schemas.BifrostResponsesRequest{
		Provider: schemas.Bedrock,
		Model:    model,
		Input: []schemas.ResponsesMessage{
			{Role: &user, Content: &schemas.ResponsesMessageContent{ContentStr: &q}},
			*reasoning,
			{Role: &assistant, Content: &schemas.ResponsesMessageContent{ContentStr: &a}},
			{Role: &user, Content: &schemas.ResponsesMessageContent{ContentStr: &q2}},
		},
	}
}

func TestUnsignedReasoningReplay_Responses(t *testing.T) {
	ctx := schemas.NewBifrostContext(context.Background(), schemas.NoDeadline)
	signature := "EqQBCgIYAhIM...fixture"
	reasoningType := schemas.ResponsesMessageTypeReasoning

	summaryOnly := func() *schemas.ResponsesMessage {
		return &schemas.ResponsesMessage{Type: &reasoningType, ResponsesReasoning: &schemas.ResponsesReasoning{
			Summary: []schemas.ResponsesReasoningSummary{{Text: "thought about it"}},
		}}
	}
	contentBlockUnsigned := func() *schemas.ResponsesMessage {
		return &schemas.ResponsesMessage{Type: &reasoningType,
			Content:            &schemas.ResponsesMessageContent{ContentBlocks: []schemas.ResponsesMessageContentBlock{reasoningTextBlock("thought about it", nil)}},
			ResponsesReasoning: &schemas.ResponsesReasoning{},
		}
	}
	signedSummary := func() *schemas.ResponsesMessage {
		return &schemas.ResponsesMessage{Type: &reasoningType, ResponsesReasoning: &schemas.ResponsesReasoning{
			Summary:          []schemas.ResponsesReasoningSummary{{Text: "thought about it"}},
			EncryptedContent: &signature,
		}}
	}
	twoSummariesOneSignature := func() *schemas.ResponsesMessage {
		return &schemas.ResponsesMessage{Type: &reasoningType, ResponsesReasoning: &schemas.ResponsesReasoning{
			Summary:          []schemas.ResponsesReasoningSummary{{Text: "first"}, {Text: "second"}},
			EncryptedContent: &signature,
		}}
	}

	t.Run("claude drops an unsigned summary block", func(t *testing.T) {
		req, err := ToBedrockResponsesRequest(ctx, responsesReplayWithReasoning(unsignedReasoningClaude, summaryOnly()))
		require.NoError(t, err)
		require.Empty(t, reasoningBlocksInConverse(req.Messages),
			"Claude rejects a thinking block without a signature (\"thinking.signature: Field required\"); the unsigned block must not be replayed")
	})
	t.Run("claude drops an unsigned reasoning content block", func(t *testing.T) {
		req, err := ToBedrockResponsesRequest(ctx, responsesReplayWithReasoning(unsignedReasoningClaude, contentBlockUnsigned()))
		require.NoError(t, err)
		require.Empty(t, reasoningBlocksInConverse(req.Messages))
	})
	t.Run("claude keeps a signed summary block", func(t *testing.T) {
		req, err := ToBedrockResponsesRequest(ctx, responsesReplayWithReasoning(unsignedReasoningClaude, signedSummary()))
		require.NoError(t, err)
		blocks := reasoningBlocksInConverse(req.Messages)
		require.Len(t, blocks, 1)
		require.NotNil(t, blocks[0].ReasoningContent.ReasoningText.Signature)
		require.Equal(t, signature, *blocks[0].ReasoningContent.ReasoningText.Signature)
	})
	t.Run("claude keeps only the signed first summary of several", func(t *testing.T) {
		req, err := ToBedrockResponsesRequest(ctx, responsesReplayWithReasoning(unsignedReasoningClaude, twoSummariesOneSignature()))
		require.NoError(t, err)
		blocks := reasoningBlocksInConverse(req.Messages)
		require.Len(t, blocks, 1, "the second summary entry has no signature of its own and would be rejected by Claude")
		require.Equal(t, "first", *blocks[0].ReasoningContent.ReasoningText.Text)
		require.NotNil(t, blocks[0].ReasoningContent.ReasoningText.Signature)
	})
	t.Run("nova keeps an unsigned summary block with no signature field", func(t *testing.T) {
		req, err := ToBedrockResponsesRequest(ctx, responsesReplayWithReasoning(unsignedReasoningNova, summaryOnly()))
		require.NoError(t, err)
		blocks := reasoningBlocksInConverse(req.Messages)
		require.Len(t, blocks, 1)
		require.Nil(t, blocks[0].ReasoningContent.ReasoningText.Signature, "Nova rejects a present-but-empty signature")
	})
	t.Run("nova keeps both unsigned summaries", func(t *testing.T) {
		req, err := ToBedrockResponsesRequest(ctx, responsesReplayWithReasoning(unsignedReasoningNova, twoSummariesOneSignature()))
		require.NoError(t, err)
		require.Len(t, reasoningBlocksInConverse(req.Messages), 2)
	})
}

func chatReplayWithReasoning(model string, details []schemas.ChatReasoningDetails) *schemas.BifrostChatRequest {
	return &schemas.BifrostChatRequest{
		Provider: schemas.Bedrock,
		Model:    model,
		Input: []schemas.ChatMessage{
			{Role: schemas.ChatMessageRoleUser, Content: &schemas.ChatMessageContent{ContentStr: schemas.Ptr("hello")}},
			{Role: schemas.ChatMessageRoleAssistant, Content: &schemas.ChatMessageContent{ContentStr: schemas.Ptr("hi there")},
				ChatAssistantMessage: &schemas.ChatAssistantMessage{ReasoningDetails: details}},
			{Role: schemas.ChatMessageRoleUser, Content: &schemas.ChatMessageContent{ContentStr: schemas.Ptr("Reply with just the word ok.")}},
		},
	}
}

func TestUnsignedReasoningReplay_Chat(t *testing.T) {
	ctx := schemas.NewBifrostContext(context.Background(), schemas.NoDeadline)
	signature := "EqQBCgIYAhIM...fixture"
	unsigned := []schemas.ChatReasoningDetails{{Index: 0, Type: schemas.BifrostReasoningDetailsTypeText, Text: schemas.Ptr("thought about it")}}
	signed := []schemas.ChatReasoningDetails{{Index: 0, Type: schemas.BifrostReasoningDetailsTypeText, Text: schemas.Ptr("thought about it"), Signature: &signature}}

	t.Run("claude drops an unsigned reasoning detail", func(t *testing.T) {
		req, err := ToBedrockChatCompletionRequest(ctx, chatReplayWithReasoning(unsignedReasoningClaude, unsigned))
		require.NoError(t, err)
		require.Empty(t, reasoningBlocksInConverse(req.Messages),
			"Claude rejects a thinking block without a signature; the unsigned detail must not be replayed")
	})
	t.Run("claude keeps a signed reasoning detail", func(t *testing.T) {
		req, err := ToBedrockChatCompletionRequest(ctx, chatReplayWithReasoning(unsignedReasoningClaude, signed))
		require.NoError(t, err)
		blocks := reasoningBlocksInConverse(req.Messages)
		require.Len(t, blocks, 1)
		require.NotNil(t, blocks[0].ReasoningContent.ReasoningText.Signature)
	})
	t.Run("nova keeps an unsigned reasoning detail with no signature field", func(t *testing.T) {
		req, err := ToBedrockChatCompletionRequest(ctx, chatReplayWithReasoning(unsignedReasoningNova, unsigned))
		require.NoError(t, err)
		blocks := reasoningBlocksInConverse(req.Messages)
		require.Len(t, blocks, 1)
		require.Nil(t, blocks[0].ReasoningContent.ReasoningText.Signature)
	})
}

func TestUnsignedReasoningReplayEmbeddedContent(t *testing.T) {
	for name, signature := range map[string]*string{"absent": nil, "empty": schemas.Ptr("")} {
		for _, withText := range []bool{false, true} {
			t.Run(name+"/withText="+fmt.Sprint(withText), func(t *testing.T) {
				blocks := []schemas.ResponsesMessageContentBlock{{Type: schemas.ResponsesOutputMessageContentTypeReasoning, Text: schemas.Ptr("thinking"), Signature: signature}}
				if withText {
					blocks = append(blocks, schemas.ResponsesMessageContentBlock{Type: schemas.ResponsesOutputMessageContentTypeText, Text: schemas.Ptr("answer")})
				}
				req, err := ToBedrockResponsesRequest(schemas.NewBifrostContext(context.Background(), schemas.NoDeadline), &schemas.BifrostResponsesRequest{
					Provider: schemas.Bedrock, Model: unsignedReasoningClaude,
					Input: []schemas.ResponsesMessage{
						{Role: schemas.Ptr(schemas.ResponsesInputMessageRoleUser), Content: &schemas.ResponsesMessageContent{ContentStr: schemas.Ptr("hello")}},
						{Type: schemas.Ptr(schemas.ResponsesMessageTypeMessage), Role: schemas.Ptr(schemas.ResponsesInputMessageRoleAssistant), Content: &schemas.ResponsesMessageContent{ContentBlocks: blocks}},
						{Role: schemas.Ptr(schemas.ResponsesInputMessageRoleUser), Content: &schemas.ResponsesMessageContent{ContentStr: schemas.Ptr("continue")}},
					},
				})
				require.NoError(t, err)
				require.Empty(t, reasoningBlocksInConverse(req.Messages))
				require.Len(t, req.Messages, 3, "preserve the assistant turn, as Chat conversion does")
				for _, msg := range req.Messages {
					require.NotEmpty(t, msg.Content, "Converse requires non-empty content")
				}
				require.Len(t, req.Messages[1].Content, 1)
				require.NotNil(t, req.Messages[1].Content[0].Text)
				if withText {
					require.Equal(t, "answer", *req.Messages[1].Content[0].Text)
				} else {
					require.NotEmpty(t, *req.Messages[1].Content[0].Text)
				}
			})
		}
	}
}
